[workspace]
resolver = "2"
members = ["crates/proto", "crates/firmware", "crates/littlefs2-sys", "crates/boot"]
exclude = ["build/lfstest"]

[patch.crates-io]
littlefs2-sys = { path = "crates/littlefs2-sys" }

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
debug = 1
